### ISSUE TITLE
[ERROR] Only annotation mapping is supported by make:entity after upgrading bundles

### ISSUE THREAD

**Issue by thomas2411** [symfony/maker-bundle#841]
After upgrading bundles like this:
```
Upgrading doctrine/doctrine-bundle (2.2.3 => 2.3.0)
Upgrading doctrine/migrations (3.1.0 => 3.1.1)
Upgrading symfony/doctrine-bridge (v5.2.4 => v5.2.5)
Upgrading symfony/maker-bundle (v1.29.1 => v1.30.0)  
```

when I try to change or add a new entity like:

`php bin/console make:entity MyEntity` I get error

```
Only annotation mapping is supported by make:entity, but the <info>App\Entity\MyEntity</info>       
class uses a different format. If you would like this command to generate the properties & getter/setter       
methods, add your mapping configuration, and then re-run this command with the <info>--regenerate</info>       
flag. 
```

When I have downgraded to previous version it works OK.

**Comment by cpoint-eu** [comment]
Same problem here:

`
- Upgrading doctrine/doctrine-bundle (2.2.4 => 2.3.0)
- Upgrading symfony/maker-bundle (v1.29.1 => v1.30.0)
`

**Comment by connorhu** [comment]
The getMetadataDriverImpl method returns different things in the two versions.

In v2.2.4 it returns Doctrine\Persistence\Mapping\Driver\MappingDriverChain
In v2.3.0 it returns Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver

https://github.com/symfony/maker-bundle/blob/main/src/Doctrine/DoctrineHelper.php#L98-L110

**Comment by bechir** [comment]
Same problem with `v1.30.0`

**Comment by dcognata** [comment]
Same problem with clean project:

doctrine/doctrine-bundle 2.3.0
symfony/maker-bundle 1.30.0

Work fine with doctrine/doctrine-bundle 2.2.4 and symfony/maker-bundle 1.30.0

**Comment by Geekimo** [comment]
Found problem and fix.
PR 1284 in DoctrineBundle added a new MappingDriver, that adds a new step to access the MappingDriverChain from the MakeEntity command.
I'm doing a PR right now.

**Comment by Geekimo** [comment]
Just pushed PR #843 to fix this issue, but will need #1304 from doctrine bundle to be merged.

**Comment by weaverryan** [comment]
Fixed now in 1.30.1  :)

**Comment by abul-wcse** [comment]
I'm still having the same issue even with 1.31.0. my PHP version is 8 if that makes any difference

**Comment by dsentker** [comment]
I can confirm that 1.30.2 has fixed the problem (PHP 7.4)

**Comment by abul-wcse** [comment]
steps to reproduce 

- symfony new --dir=~/Working/personal/maker-test --no-git --full
- cd symfony-test
- Replace the App in name to Custom
- Update the PSR4 settings in composer.json 
- composer dump-autoload
- create a new file in the config/package directory called maker.yaml and add
```
maker:
  root_namespace: 'Custom'
```
- bin/console make:entity NewEntity
I get the following error
<img width="947" alt="Screenshot 2021-05-11 at 5 07 35 pm" src="https://user-images.githubusercontent.com/11312568/117848747-7e9ef400-b27b-11eb-94ac-6ed76e741451.png">

Here is a the simple Symfony app created using the above steps @jrushlow

**Comment by ensiente** [comment]
Still having the same issue. v1.33.0

**Comment by bastien70** [comment]
We still have the issue with latest symfony version and doctrine version.
When using PHP 8 attributes for doctrine, we can not use the maker to add/modify entity

**Comment by reksc** [comment]
Same issue on 1.36 with PHP 8 attributes for doctrine.

**Comment by planet17** [comment]
Same issue on 1.38 with PHP 8.1 with custom root_namespace.

**Comment by thomas2411** [comment]
Problem reappeared. I have just upgraded all bundles and with version 1.38 error appears again (PHP 8.1). Tweaking a little bit with versions showed that the reason is upgrading **doctrine/orm (2.11.3 => 2.12.0)**

**Comment by ShiNoSenshi** [comment]
I'm using PHP 8.1 and after upgrading to 1.44 this bug reappeared for me again. Downgrading to 1.43 fixed it.

**Comment by jrushlow** [comment]
Are u using attributes for you're entity mapping?

**Comment by ShiNoSenshi** [comment]
I debugged into the error message and found out, that it uses AnnotationDriver instead of the expected AttributeDriver. Can you tell me where in my config I have to change the setting?

**Comment by UtechtDustin** [comment]
> I'm using PHP 8.1 and after upgrading to 1.44 this bug reappeared for me again. Downgrading to 1.43 fixed it.
Thanks, works for me ! :-)

**Comment by ShiNoSenshi** [comment]
What also worked for me:

- I removed the **type: attribute** in my doctrine.yaml
- ran the rector DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES set.
- had to update some JoinTable configs in the updated annotations.
- now I can work with 1.44

**Comment by ahmadsajid1989** [comment]
This issue comes back again on maker bundle 1.45, downgrading to 1.43 solved the issue for me

**Comment by olegrand1976** [comment]
> This issue comes back again on maker bundle 1.45, downgrading to 1.43 solved the issue for me

Hello, 

Work fine for me! 

Php version 8.1.8
Composer version 2.3.7
Symfony CLI version 5.4.12

I have modified :

**Composer.json :**

"doctrine/doctrine-bundle": "^2.7.0" -> v2.7.0 installed
"symfony/maker-bundle": "^1.43" -> 1.45  installed ==> **replaced by "symfony/maker-bundle": "1.43"** 

And all is fine!

**Comment by kasteckis** [comment]
This issue should be reopened or new one created.
1.45 has this bug, had to downgrade to 1.43.

`composer update symfony/maker-bundle:1.43.0`

**Comment by hugoderre** [comment]
Same here, have to downgrade maker-bundle from 1.45 to 1.43

**Comment by robibubble** [comment]
> Same here, have to downgrade maker-bundle from 1.45 to 1.43
Can Confirm.

**Comment by imajim** [comment]
> > Same here, have to downgrade maker-bundle from 1.45 to 1.43
> 
> Can Confirm.

I confirm, it's working.

` php8 composer.phar update  symfony/maker-bundle:1.43.0
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading symfony/maker-bundle (v1.45.0 => v1.43.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading symfony/maker-bundle (v1.43.0)
  - Downgrading symfony/maker-bundle (v1.45.0 => v1.43.0): Extracting archive
`

**Comment by snipershady** [comment]
the problem persists,
it doesn't work anymore with maker bundle 1.43 too

**Comment by imreg** [comment]
This new version, sorry guys, but a piece of shit. Has a number of issues and causes issues in previous Entities where annotations were used. This is not a development or improvement and doesn't give us option to annotations. 
But if anyone has an idea how to use annotations over entity I'd like to know and learn.

**Comment by NetworkDevHead** [comment]
It is super frustrating when Symfony breaks core tooling outside of the promised version lifecycles

**Comment by vipinbose** [comment]
Remove **type: annotation** from doctrine.yaml
